export const strings = {
  mobileInfo: 'Mobile Info',
  enterMobileNumber: 'Enter mobile number',
  enterOTP: 'Enter otp number',
  sendOTP: 'Send OTP',
  login: 'Login',
  welcome: 'Welcome',
  pleaseEnterMobile: 'Please enter mobile number',
  validMobile: 'Enter valid mobile number',
  pleaseEnterOTP: 'Please enter otp number',
  validOTP: 'Enter valid OTP',
  profile: 'Profile',
  editProfile: 'Edit Profile',
  home: 'Home',
  logout: 'Logout',
  firstName: 'First name',
  lastName: 'Last name',
  email: 'Email',
  mobileNumber: 'Mobile number',

  enterFirstName: 'Enter first name',
  enterLastName: 'Enter last name',
  enterEmail: 'Enter email',
  update: 'Update',

  pleaseEnterFirstName: 'Please enter first name',
  pleaseEnterLastName: 'Please enter last name',
  pleaseEnterEmail: 'Please enter email',
  pleaseEnterValidEmail: 'Please enter valid email',
};
