export const screenName = {
  PRE_LOGIN: 'PRE_LOGIN',
  POST_LOGIN: 'POST_LOGIN',
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  OTP_SCREEN: 'OTP_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  EDIT_PROFILE_SCREEN: 'EDIT_PROFILE_SCREEN',
};
